# Generated by Django 5.2.12 on 2026-03-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='hp_current',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='hp_max',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=1, max_length=50),
        ),
    ]
