# Generated by Django 5.2.12 on 2026-03-24 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_charisma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_class',
            new_name='character_class',
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
