# Generated by Django 5.2.12 on 2026-06-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_alignment_character_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='armor_class_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('shield', 'Shield'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
