# Generated by Django 5.2.12 on 2026-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_inventoryitem_armor_class_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='damage_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='damage_dice',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('slashing', 'Slashing'), ('piercing', 'Piercing'), ('bludgeoning', 'Bludgeoning'), ('fire', 'Fire'), ('cold', 'Cold'), ('lightning', 'Lightning'), ('poison', 'Poison'), ('acid', 'Acid'), ('thunder', 'Thunder'), ('necrotic', 'Necrotic'), ('radiant', 'Radiant'), ('force', 'Force'), ('psychic', 'Psychic')], default='', max_length=20),
        ),
    ]
