# Generated by Django 5.2.12 on 2026-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_inventoryitem_damage_bonus_inventoryitem_damage_dice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='proficient_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='spell',
            name='requires_concentration',
            field=models.BooleanField(default=False),
        ),
    ]
