# Generated by Django 5.2.12 on 2026-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_character_proficient_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollhistory',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
