# Generated by Django 5.2.12 on 2026-07-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_profile_rollhistory_character_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollhistory',
            name='discarded_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollhistory',
            name='roll_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('advantage', 'Advantage'), ('disadvantage', 'Disadvantage')], default='normal', max_length=15),
        ),
    ]
